# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# [](bg-1)\

# Use zero width joiner \u200B to get a character we can apply styling to
# this makes "prev_fg" work

# use conditional matching to only show space if something is there
# ([ ](bg:prev_bg fg:light)\

format = """
[ $username@$hostname ](bg:bg-1 fg:dark)\
[](bg:bg-2 fg:prev_bg)\
[\u200B](bg:prev_bg fg:dark)\
$directory\
[](fg:prev_bg bg:bg-3)\
([ ](bg:prev_bg fg:dark)\
$git_branch\
$git_status\
)\
[](fg:prev_bg bg:bg-4)\
([ ](bg:prev_bg fg:dark)\
[\
$c\
$cmake\
$daml\
$deno\
$dotnet\
$elixir\
$elm\
$erlang\
$fennel\
$golang\
$haskell\
$helm\
$java\
$julia\
$kotlin\
$gradle\
$lua\
$nodejs\
$opa\
$perl\
$python\
$rust\
$terraform\
$vlang\
$vagrant\
$nix_shell\
$conda\
$meson\
$spack\
$aws\
$gcloud\
$openstack\
$azure\
$crystal\
$jobs\
](bg:prev_bg)\
)\
[](fg:prev_bg bg:bg-5)\
([ ](bg:prev_bg fg:dark)\
$package\
$docker_context\
)\
[](fg:prev_bg bg:bg-6)\
([ ](bg:prev_bg fg:light)\
$env_var\
$memory_usage\
$custom\
$sudo\
$cmd_duration\
$character\
$status\
)\
[ ](fg:prev_bg)\
$line_break\
[](fg:bg-1)\
"""
#[╚═❯ ](fg:bg-1)\
#[╚═❯ ](fg:bg-4)\
#[┕━❯╰─\uea9c╚═❯](fg:bg-4)\


add_newline = true

palette = 'map'

[palettes.map]
light = "white"
dark = "black"
bg-1 = "#9A348E"
bg-2 = "#DA627D"
bg-3 = "#FCA17D"
bg-4 = "#86BBD8"
bg-5 = "#06969A"
bg-6 = "#33658A"


# You can also replace your username with a neat symbol like   or disable this
# and use the os module below
[username]
show_always = true
#style_user = "bg:bg-1"
#style_root = "bg:bg-1"
format = '$user'
disabled = false

# An alternative to the username module which displays a symbol that
# represents the current operating system
[os]
style = "bg:prev"
disabled = true   # Disabled by default

[hostname]
ssh_only = false
style = "bg:prev_bg fg:dark bold italic"
format = "[$hostname]($style)"
trim_at = ''
disabled = false

[directory]
style = "bg:prev_bg fg:prev_fg"
format = "[ $path ]($style)"
fish_style_pwd_dir_length = 1
truncation_length = 0
truncation_symbol = "…/"

# Here is how you can shorten some long paths by text replacement
# similar to mapped_locations in Oh My Posh:
[directory.substitutions]
"Documents" = " "
"Downloads" = " "
"Music" = " "
"Pictures" = " "
# Keep in mind that the order matters. For example:
# "Important Documents" = "  "
# will not be replaced, because "Documents" was already substituted before.
# So either put "Important Documents" before "Documents" or use the substituted version:
# "Important  " = "  "


[package]
display_private = true
style = "bold bg:prev_bg fg:prev_fg"
format = '[$symbol$version ]($style)'

[cmd_duration]
style = "bg:prev_bg fg:prev_fg"
min_time = 500
format = "[$duration ]($style)"

# https://starship.rs/config/#status
[status]
style = "bg:prev_bg fg:prev_fg"
# style = "bold red bg:prev_bg"
format = "[$symbol$status ]($style)"
disabled = false

# https://starship.rs/config/#character
[character]
success_symbol = ''
error_symbol = ''
vimcmd_symbol = "n "
vimcmd_visual_symbol = "v "
vimcmd_replace_one_symbol = "r "
vimcmd_replace_symbol = "R "
format = "[$symbol](bg:prev_bg fg:prev_fg italic)"

# Languages

[c]
symbol = ""
style = "bg:prev_bg fg:prev_fg"
format = '[$symbol ($version) ]($style)'

[docker_context]
symbol = ""
style = "bg:prev_bg fg:prev_fg"
format = '[$symbol $context ]($style) $path'

[elm]
symbol = ""
style = "bg:prev_bg fg:prev_fg"
format = '[$symbol ($version) ]($style)'

[git_branch]
symbol = ""
style = "bg:prev_bg fg:prev_fg"
format = '[$symbol $branch ]($style)'

[git_status]
style = "bg:prev_bg fg:prev_fg"
format = '[$all_status$ahead_behind ]($style)'

[golang]
symbol = ""
style = "bg:prev_bg fg:prev_fg"
format = '[$symbol ($version) ]($style)'

[gradle]
style = "bg:prev_bg fg:prev_fg"
format = '[$symbol ($version) ]($style)'

[haskell]
symbol = ""
style = "bg:prev_bg fg:prev_fg"
format = '[$symbol ($version) ]($style)'

[java]
symbol = ""
style = "bg:prev_bg fg:prev_fg"
format = '[$symbol ($version) ]($style)'

[julia]
symbol = ""
style = "bg:prev_bg fg:prev_fg"
format = '[$symbol ($version) ]($style)'

# Needs extra space
[lua]
symbol = ""
style = "bg:prev_bg fg:prev_fg"
format = '[$symbol  ($version) ]($style)'

[nodejs]
symbol = ""
style = "bg:prev_bg fg:prev_fg"
format = '[$symbol ($version) ]($style)'

[rust]
symbol = ""
style = "bg:prev_bg fg:prev_fg"
format = '[$symbol ($version) ]($style)'

[python]
symbol = " "
style = "bg:prev_bg fg:prev_fg"
format = '[$symbol ($version) ]($style)'
