#!/bin/sh
xrandr --output HDMI-0 --auto --scale 1.5x1.5 --output DP-2 --auto --pos 1620x360 &
xsetroot -cursor_name left_ptr &
export GDK_SCALE=2 &
export SSH_AUTH_SOCK=$XDG_RUNTIME_DIR/ssh-agent.socket &
export QT_QPA_PLATFORMTHEME=qt5ct &
